### ISSUE TITLE
feature request: a "one file" release

### ISSUE THREAD

**Issue by vletoux** [ANSSI-FR/OVALI#2]
When distributing reports for some management people, it is difficult to release json file with the viewer.
Indeed, the size is smaller with json file but the report cannot be shared easily using email except by making an image file. But the current export doesn't include the name of the nodes of the graph.

The idea would be to release a single file with comments inside where the json file can be copied / pasted here.

**Comment by zefr0g** [comment]
If you want to display node names on the graph, you can use the `label` property of the `Vizu.options.data.properties.nodes` object in `config.js` and use whatever field you want to display on the nodes. This way the exported png will show nodes names.

Releasing a single file would require including all assets (js & css) inline in the `index.html` file and calling the `graph.setData` function. It's not that complicated but would make the tool a lot less maintainable.

**Comment by vletoux** [comment]
This works like a charm. I'm able to have a 400kB minimized file which can be sent easily by email.
The tricks is to escape the backslash character when the json content is copy/paster in the html source.

I've 2 remarks:
1) Is it possible to add general information to the json file which can then be displayed ?
(creation date and some properties like that)
2) I've built a json file to have a map of some active directory trusts (>90).
As is, the color of the node is hardcoded in your source code (domain = grey, unknown = purple circle, ...)
I've added the name of the domain using the trick you used but there is too much domains to have something visible.
I'd like also to color some links. Indeed a trust with SID FIltering (quarantined) is better than a trust without SID Filtering.
I'd like to share my json file with you but it contains sensitive information.
Can I send it to you at the ANSSI so you can tell me what do you think about and how I can make it more readable ?
